name: Tide CI/CD

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Analyze code and generate the documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.4.0-4.2.pre"
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze --congratulate --no-pub --preamble --fatal-infos --fatal-warnings
      - name: Check dart code format
        run: flutter format --output=none --set-exit-if-changed .
      - name: Generate documentation
        run: |
          flutter pub global activate dartdoc
          dartdoc --exclude dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart,dart:ffi,dart:html,dart:js,dart:ui,dart:js_util
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: doc/api

  release:
    runs-on: ubuntu-20.04
    name: Create a release
    needs: [lint]
    if: github.event_name == 'push' && contains(github.ref, 'master') || contains(github.ref, 'cicd/')
    steps:
      - name: Create a release for Tide
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: "Ref: ${{ github.ref }} SHA: ${{ github.sha }}"
          draft: true
          prerelease: false
