name: Zéphyr CI/CD

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Check that the Dart source code is correctly formatted.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.4.0-4.2.pre"
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze --congratulate --no-pub --preamble --fatal-infos --fatal-warnings
      - name: Run dart format
        run: flutter format --output=none --set-exit-if-changed .

  # TODO: Generate the documentation

  release:
    runs-on: ubuntu-18.04
    name: Create a release
    needs: [lint]
    if: github.event_name == 'push' && contains(github.ref, 'master') || contains(github.ref, 'cicd/')
    steps:
      - name: Create a release for Zéphyr
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: "Ref: ${{ github.ref }} SHA: ${{ github.sha }}"
          draft: true
          prerelease: false
